import React from "react";

export default function BlogLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main
      style={{
        maxWidth: 700,
        margin: "auto",
        // padding: "1.5rem",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        lineHeight: 1.6,
      }}
    >
      {children}
      <p
        style={{
          marginTop: "2rem",
          fontStyle: "italic",
          fontSize: "0.9rem",
          color: "#555",
        }}
      >
        This content is generated by AI.
      </p>
    </main>
  );
}
